### ISSUE TITLE
x-axis ticks

### ISSUE THREAD

**Issue by ColinAnthony** [davidmatten/chaosplot#3]
Consider whether it is better to hard set the x-axis based on the values in wpi column (equal spacing between each time point), rather than to have 3 separate x-axis ranges.

**Comment by davidmatten** [comment]
For the general method, a chaos plot which can accept any data set and is not customized: it is better to have only one set of axes. This is how this function has been altered.

It might be better to alter the chaos plot method to draw onto a set of axes which is passed as an argument. Then, the user calling the chaosplot function could create those three (or however many) axes, and scale them to their own desires.
